<?xml version="1.0" encoding="utf-8"?><Database Name="ANS_SEIS_TV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NATHANIEL-VX15;Initial Catalog=ANS_SEIS_TV;Integrated Security=True" SettingsObjectName="ANS_SEIS_TV.Properties.Settings" SettingsPropertyName="ANS_SEIS_TVConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EQUIPMENT_DESIGNATION" Member="EQUIPMENT_DESIGNATIONs">
    <Type Name="EQUIPMENT_DESIGNATION">
      <Column Name="EQ_DESIGNATION_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_DESIGNATED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DATE_RETURNED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DESIGNATION_STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_EQUIPMENT_DESIGNATION" Member="TBLUSERDETAIL" ThisKey="ID" OtherKey="ID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.USERTYPE" Member="USERTYPEs">
    <Type Name="USERTYPE">
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERTYPE_DESCRIPTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="USERTYPE_TBLSTUDENTDETAIL" Member="TBLSTUDENTDETAILs" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="TBLSTUDENTDETAIL" />
      <Association Name="USERTYPE_TBLUSERDETAIL" Member="TBLUSERDETAILs" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="TBLUSERDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.REQUESTSTATUS" Member="REQUESTSTATUS">
    <Type Name="REQUESTSTATUS">
      <Column Name="REQUESTSTATUSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATUSDESCRIPTION" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="REQUESTSTATUS_TBLREQUESTTABLE" Member="TBLREQUESTTABLEs" ThisKey="REQUESTSTATUSID" OtherKey="REQUESTSTATUSID" Type="TBLREQUESTTABLE" />
    </Type>
  </Table>
  <Table Name="dbo.TBLBORRIWINGBARCODE" Member="TBLBORRIWINGBARCODEs">
    <Type Name="TBLBORRIWINGBARCODE">
      <Column Name="BarcodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BorrowingBarcode" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BWBarcodePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TBLTRANSACTION_TBLBORRIWINGBARCODE" Member="TBLTRANSACTION" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLTRANSACTION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLBORROWED" Member="TBLBORROWEDs">
    <Type Name="TBLBORROWED">
      <Column Name="BorrowID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATEBORROWED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsReturned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLBORROWED" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
      <Association Name="TBLTRANSACTION_TBLBORROWED" Member="TBLTRANSACTION" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLTRANSACTION" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLBORROWED" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLBORROWQUANTITY" Member="TBLBORROWQUANTITies">
    <Type Name="TBLBORROWQUANTITY">
      <Column Name="BORROWID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLBORROWQUANTITY" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLDEPLOYMENT" Member="TBLDEPLOYMENTs">
    <Type Name="TBLDEPLOYMENT">
      <Column Name="DeploymentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FacilitiyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLFACILITy_TBLDEPLOYMENT" Member="TBLFACILITy" ThisKey="FacilitiyID" OtherKey="FacilityID" Type="TBLFACILITy" IsForeignKey="true" />
      <Association Name="TBLTRANSACTION_TBLDEPLOYMENT" Member="TBLTRANSACTION" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLTRANSACTION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTBARCODE" Member="TBLEQUIPMENTBARCODEs">
    <Type Name="TBLEQUIPMENTBARCODE">
      <Column Name="BarcodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Equipment_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipmentBarcode" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EQBarcodepath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTBARCODE" Member="TBLEQUIPMENTDETAIL" ThisKey="Equipment_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTDETAILS" Member="TBLEQUIPMENTDETAILs">
    <Type Name="TBLEQUIPMENTDETAIL">
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISBORROWABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLBORROWED" Member="TBLBORROWEDs" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLBORROWED" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLBORROWQUANTITY" Member="TBLBORROWQUANTITies" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLBORROWQUANTITY" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTBARCODE" Member="TBLEQUIPMENTBARCODEs" ThisKey="EQUIPMENT_ID" OtherKey="Equipment_ID" Type="TBLEQUIPMENTBARCODE" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTRESERVATION" Member="TBLEQUIPMENTRESERVATIONs" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTRESERVATION" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTSTATUS" Member="TBLEQUIPMENTSTATUS" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTSTATUS" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLPULLEDOUTEQUIPMENT" Member="TBLPULLEDOUTEQUIPMENTs" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLPULLEDOUTEQUIPMENT" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLRETURNEDEQUIPMENT" Member="TBLRETURNEDEQUIPMENTs" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLRETURNEDEQUIPMENT" />
      <Association Name="TBLEQUIPMENTTYPE_TBLEQUIPMENTDETAIL" Member="TBLEQUIPMENTTYPE" ThisKey="EQUIPMENT_TYPE_ID" OtherKey="EQUIPMENT_TYPE_ID" Type="TBLEQUIPMENTTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTRESERVATION" Member="TBLEQUIPMENTRESERVATIONs">
    <Type Name="TBLEQUIPMENTRESERVATION">
      <Column Name="ReservationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateReserved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsReturned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTRESERVATION" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
      <Association Name="TBLTRANSACTION_TBLEQUIPMENTRESERVATION" Member="TBLTRANSACTION" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLTRANSACTION" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLEQUIPMENTRESERVATION" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTSTATUS" Member="TBLEQUIPMENTSTATUS">
    <Type Name="TBLEQUIPMENTSTATUS">
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GoodCondition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BadCondition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLEQUIPMENTSTATUS" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTTYPE" Member="TBLEQUIPMENTTYPEs">
    <Type Name="TBLEQUIPMENTTYPE">
      <Column Name="EQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_TYPE_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTTYPE_TBLEQUIPMENTDETAIL" Member="TBLEQUIPMENTDETAILs" ThisKey="EQUIPMENT_TYPE_ID" OtherKey="EQUIPMENT_TYPE_ID" Type="TBLEQUIPMENTDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.TBLFACILITIES" Member="TBLFACILITies">
    <Type Name="TBLFACILITy">
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FacilityName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FacilityType" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FacilityRoomNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBLFACILITy_TBLDEPLOYMENT" Member="TBLDEPLOYMENTs" ThisKey="FacilityID" OtherKey="FacilitiyID" Type="TBLDEPLOYMENT" />
      <Association Name="TBLUSERDETAIL_TBLFACILITy" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLPULLEDOUTEQUIPMENT" Member="TBLPULLEDOUTEQUIPMENTs">
    <Type Name="TBLPULLEDOUTEQUIPMENT">
      <Column Name="PullOutID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLPULLEDOUTEQUIPMENT" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLREQUESTREPLY" Member="TBLREQUESTREPLies">
    <Type Name="TBLREQUESTREPLY">
      <Column Name="ReplyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="REQUESTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReplyContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateReplied" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLREQUESTTABLE_TBLREQUESTREPLY" Member="TBLREQUESTTABLE" ThisKey="REQUESTID" OtherKey="REQUESTID" Type="TBLREQUESTTABLE" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLREQUESTREPLY" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLREQUESTTABLE" Member="TBLREQUESTTABLEs">
    <Type Name="TBLREQUESTTABLE">
      <Column Name="REQUESTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REQUESTHEADER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REQUESTCONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATEREQUESTED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REQUESTSTATUSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISOPENED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLREQUESTTABLE_TBLREQUESTREPLY" Member="TBLREQUESTREPLies" ThisKey="REQUESTID" OtherKey="REQUESTID" Type="TBLREQUESTREPLY" />
      <Association Name="REQUESTSTATUS_TBLREQUESTTABLE" Member="REQUESTSTATUS" ThisKey="REQUESTSTATUSID" OtherKey="REQUESTSTATUSID" Type="REQUESTSTATUS" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLREQUESTTABLE" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLRETURNEDEQUIPMENTS" Member="TBLRETURNEDEQUIPMENTs">
    <Type Name="TBLRETURNEDEQUIPMENT">
      <Column Name="ReturnID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQUIPMENTDETAIL_TBLRETURNEDEQUIPMENT" Member="TBLEQUIPMENTDETAIL" ThisKey="EQUIPMENT_ID" OtherKey="EQUIPMENT_ID" Type="TBLEQUIPMENTDETAIL" IsForeignKey="true" />
      <Association Name="TBLTRANSACTION_TBLRETURNEDEQUIPMENT" Member="TBLTRANSACTION" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLTRANSACTION" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLRETURNEDEQUIPMENT" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLSTUDENTDETAILS" Member="TBLSTUDENTDETAILs">
    <Type Name="TBLSTUDENTDETAIL">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="USERTYPE_TBLSTUDENTDETAIL" Member="USERTYPE" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="USERTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLTRANSACTION" Member="TBLTRANSACTIONs">
    <Type Name="TBLTRANSACTION">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransactionEvent" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLTRANSACTION_TBLBORRIWINGBARCODE" Member="TBLBORRIWINGBARCODEs" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLBORRIWINGBARCODE" />
      <Association Name="TBLTRANSACTION_TBLBORROWED" Member="TBLBORROWEDs" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLBORROWED" />
      <Association Name="TBLTRANSACTION_TBLDEPLOYMENT" Member="TBLDEPLOYMENTs" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLDEPLOYMENT" />
      <Association Name="TBLTRANSACTION_TBLEQUIPMENTRESERVATION" Member="TBLEQUIPMENTRESERVATIONs" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLEQUIPMENTRESERVATION" />
      <Association Name="TBLTRANSACTION_TBLRETURNEDEQUIPMENT" Member="TBLRETURNEDEQUIPMENTs" ThisKey="TransactionID" OtherKey="TransactionID" Type="TBLRETURNEDEQUIPMENT" />
      <Association Name="TBLUSERDETAIL_TBLTRANSACTION" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs">
    <Type Name="TBLUSERACTIONREPORT">
      <Column Name="ActionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_TBLUSERACTIONREPORT" Member="TBLUSERDETAIL" ThisKey="ID" OtherKey="ID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERDETAILS" Member="TBLUSERDETAILs">
    <Type Name="TBLUSERDETAIL">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISFIRSTLOGIN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_EQUIPMENT_DESIGNATION" Member="EQUIPMENT_DESIGNATIONs" ThisKey="ID" OtherKey="ID" Type="EQUIPMENT_DESIGNATION" />
      <Association Name="TBLUSERDETAIL_TBLBORROWED" Member="TBLBORROWEDs" ThisKey="GENID" OtherKey="GENID" Type="TBLBORROWED" />
      <Association Name="TBLUSERDETAIL_TBLEQUIPMENTRESERVATION" Member="TBLEQUIPMENTRESERVATIONs" ThisKey="GENID" OtherKey="GENID" Type="TBLEQUIPMENTRESERVATION" />
      <Association Name="TBLUSERDETAIL_TBLFACILITy" Member="TBLFACILITies" ThisKey="GENID" OtherKey="GENID" Type="TBLFACILITy" />
      <Association Name="TBLUSERDETAIL_TBLREQUESTREPLY" Member="TBLREQUESTREPLies" ThisKey="GENID" OtherKey="GENID" Type="TBLREQUESTREPLY" />
      <Association Name="TBLUSERDETAIL_TBLREQUESTTABLE" Member="TBLREQUESTTABLEs" ThisKey="GENID" OtherKey="GENID" Type="TBLREQUESTTABLE" />
      <Association Name="TBLUSERDETAIL_TBLRETURNEDEQUIPMENT" Member="TBLRETURNEDEQUIPMENTs" ThisKey="GENID" OtherKey="GENID" Type="TBLRETURNEDEQUIPMENT" />
      <Association Name="TBLUSERDETAIL_TBLTRANSACTION" Member="TBLTRANSACTIONs" ThisKey="GENID" OtherKey="GENID" Type="TBLTRANSACTION" />
      <Association Name="TBLUSERDETAIL_TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs" ThisKey="ID" OtherKey="ID" Type="TBLUSERACTIONREPORT" />
      <Association Name="TBLUSERDETAIL_TBLUSERLOGINREPORT" Member="TBLUSERLOGINREPORTs" ThisKey="ID" OtherKey="ID" Type="TBLUSERLOGINREPORT" />
      <Association Name="TBLUSERDETAIL_TBLUSERUSAGESTATISTIC" Member="TBLUSERUSAGESTATISTICs" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERUSAGESTATISTIC" />
      <Association Name="USERTYPE_TBLUSERDETAIL" Member="USERTYPE" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="USERTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERLOGINREPORT" Member="TBLUSERLOGINREPORTs">
    <Type Name="TBLUSERLOGINREPORT">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_TBLUSERLOGINREPORT" Member="TBLUSERDETAIL" ThisKey="ID" OtherKey="ID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERUSAGESTATISTICS" Member="TBLUSERUSAGESTATISTICs">
    <Type Name="TBLUSERUSAGESTATISTIC">
      <Column Name="UserCount" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalBorrowedEquipments" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_TBLUSERUSAGESTATISTIC" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_AccountRecovery" Method="sp_AccountRecovery">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SecurityQuestion" Parameter="securityQuestion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SecurityAnswer" Parameter="securityAnswer" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_AccountRecoveryResult">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewTransactionBarcode" Method="sp_ViewTransactionBarcode">
    <Parameter Name="SearchBarcode" Parameter="searchBarcode" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ViewTransactionBarcodeResult">
      <Column Name="BWBarcodePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AddUserToStatics" Method="sp_AddUserToStatics">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalBorrowedEquipments" Parameter="totalBorrowedEquipments" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BorrowAddQuantity" Method="sp_BorrowAddQuantity">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BorrowedReport" Method="sp_BorrowedReport">
    <ElementType Name="sp_BorrowedReportResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Borrowed By]" Member="Borrowed_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BorrowTeacherView" Method="sp_BorrowTeacherView">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_BorrowTeacherViewResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Borrowed By]" Member="Borrowed_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ChangePassword" Method="sp_ChangePassword">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_CurrentBorrowed" Method="sp_CurrentBorrowed">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_CurrentBorrowedResult">
      <Column Name="BARCODE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeleteDeletedEquipment" Method="sp_DeleteDeletedEquipment">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeploymentPullOut" Method="sp_DeploymentPullOut">
    <Parameter Name="RoomNo" Parameter="roomNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeploymentReport" Method="sp_DeploymentReport">
    <ElementType Name="sp_DeploymentReportResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Borrowed By]" Member="Borrowed_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FacilityRoomNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeploymentViewTeacher" Method="sp_DeploymentViewTeacher">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_DeploymentViewTeacherResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Borrowed By]" Member="Borrowed_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FacilityRoomNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentBorrowableView" Method="sp_EquipmentBorrowableView">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_EquipmentBorrowableViewResult">
      <Column Name="[Equipment ID]" Member="Equipment_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Available Quantity]" Member="Available_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentDelete" Method="sp_EquipmentDelete">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentEdit" Method="sp_EquipmentEdit">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_NAME" Parameter="eQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="EQUIPMENT_DESCRIPTION" Parameter="eQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_TYPE_ID" Parameter="eQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentID" Method="sp_EquipmentID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentQuantityEdit" Method="sp_EquipmentQuantityEdit">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentRegister" Method="sp_EquipmentRegister">
    <Parameter Name="EQUIPMENT_NAME" Parameter="eQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="EQUIPMENT_DESCRIPTION" Parameter="eQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_TYPE_ID" Parameter="eQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISBORROWABLE" Parameter="iSBORROWABLE" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentReports" Method="sp_EquipmentReports">
    <ElementType Name="sp_EquipmentReportsResult">
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EQUIPMENT_TYPE_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentReservationReport" Method="sp_EquipmentReservationReport">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_EquipmentReservationReportResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Reserved By]" Member="Reserved_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateReserved" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentReturning" Method="sp_EquipmentReturning">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Qty" Parameter="qty" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsReturned" Parameter="isReturned" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentStatusEdit" Method="sp_EquipmentStatusEdit">
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GoodCondition" Parameter="goodCondition" Type="System.Int32" DbType="Int" />
    <Parameter Name="BadCondition" Parameter="badCondition" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentStatusInventoryAdd" Method="sp_EquipmentStatusInventoryAdd">
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GoodCondition" Parameter="goodCondition" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentStatusItemDelete" Method="sp_EquipmentStatusItemDelete">
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentStatusReport" Method="sp_EquipmentStatusReport">
    <ElementType Name="sp_EquipmentStatusReportResult">
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GoodCondition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BadCondition" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentView" Method="sp_EquipmentView">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_EquipmentViewResult">
      <Column Name="[Equipment ID]" Member="Equipment_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentViewBarcode" Method="sp_EquipmentViewBarcode">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_EquipmentViewBarcodeResult">
      <Column Name="[Equipment ID]" Member="Equipment_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EquipmentBarcode" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentViewBarcodePath" Method="sp_EquipmentViewBarcodePath">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_EquipmentViewBarcodePathResult">
      <Column Name="[Equipment ID]" Member="Equipment_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQBarcodepath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewBorrow" Method="sp_NewBorrow">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WhoBorrowed" Parameter="whoBorrowed" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DATEBORROWED" Parameter="dATEBORROWED" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsReturned" Parameter="isReturned" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewBorrowBarcodeInsert" Method="sp_NewBorrowBarcodeInsert">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BorrowingBarcode" Parameter="borrowingBarcode" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="BWBarcodePath" Parameter="bWBarcodePath" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewBorrowQuantityAdded" Method="sp_NewBorrowQuantityAdded">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewDeployment" Method="sp_NewDeployment">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FacilitiyID" Parameter="facilitiyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewEquipmentBarcodeInsert" Method="sp_NewEquipmentBarcodeInsert">
    <Parameter Name="Equipment_ID" Parameter="equipment_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EquipmentBarcode" Parameter="equipmentBarcode" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" />
    <Parameter Name="EQBarcodepath" Parameter="eQBarcodepath" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewFacilities" Method="sp_NewFacilities">
    <Parameter Name="FacilityName" Parameter="facilityName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Instructor" Parameter="instructor" Type="System.Int32" DbType="Int" />
    <Parameter Name="FacilityType" Parameter="facilityType" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FacilityRoomNo" Parameter="facilityRoomNo" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewRequest" Method="sp_NewRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="REQUESTHEADER" Parameter="rEQUESTHEADER" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="REQUESTCONTENT" Parameter="rEQUESTCONTENT" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DATEREQUESTED" Parameter="dATEREQUESTED" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="REQUESTSTATUSID" Parameter="rEQUESTSTATUSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISOPENED" Parameter="iSOPENED" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewReservation" Method="sp_NewReservation">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WhoReserved" Parameter="whoReserved" Type="System.Int32" DbType="Int" />
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateBorrowed" Parameter="dateBorrowed" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsReturned" Parameter="isReturned" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewTransactionID" Method="sp_NewTransactionID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_NewTransation" Method="sp_NewTransation">
    <Parameter Name="TransactionDate" Parameter="transactionDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TransactionEvent" Parameter="transactionEvent" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PulledEquipmentsView" Method="sp_PulledEquipmentsView">
    <ElementType Name="sp_PulledEquipmentsViewResult">
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PullOutEquipment" Method="sp_PullOutEquipment">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_PullOutNewEquipment" Method="sp_PullOutNewEquipment">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="QUANTITY" Parameter="qUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RequestReplied" Method="sp_RequestReplied">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RequestResponse" Parameter="requestResponse" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RequestReply" Method="sp_RequestReply">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="REPLYCONTENT" Parameter="rEPLYCONTENT" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DateReplied" Parameter="dateReplied" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_RequestReport" Method="sp_RequestReport">
    <ElementType Name="sp_RequestReportResult">
      <Column Name="REQUESTID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Requested By]" Member="Requested_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="REQUESTHEADER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DATEREQUESTED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUSDESCRIPTION" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_RequestViewed" Method="sp_RequestViewed">
    <Parameter Name="RequestID" Parameter="requestID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ReturnedReport" Method="sp_ReturnedReport">
    <ElementType Name="sp_ReturnedReportResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Borrowed By]" Member="Borrowed_By" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReturnEquipments" Method="sp_ReturnEquipments">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="DateReturned" Parameter="dateReturned" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ReturnReservedEquipment" Method="sp_ReturnReservedEquipment">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EquipmentID" Parameter="equipmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsReturned" Parameter="isReturned" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_StudentInsert" Method="sp_StudentInsert">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_StudentSearch" Method="sp_StudentSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_StudentSearchResult">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StudentView" Method="sp_StudentView">
    <ElementType Name="sp_StudentViewResult">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TeacherApprovedClosedRequest" Method="sp_TeacherApprovedClosedRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TeacherApprovedClosedRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TeacherDeniedClosedRequest" Method="sp_TeacherDeniedClosedRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TeacherDeniedClosedRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TeacherViewAllRequest" Method="sp_TeacherViewAllRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TeacherViewAllRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TeacherViewOpenRequest" Method="sp_TeacherViewOpenRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TeacherViewOpenRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TeacherViewPendingRequest" Method="sp_TeacherViewPendingRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TeacherViewPendingRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TransactionSearchDate" Method="sp_TransactionSearchDate">
    <Parameter Name="StartDate" Parameter="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="EventType" Parameter="eventType" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_TransactionSearchDateResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Transaction Date]" Member="Transaction_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Transaction Event]" Member="Transaction_Event" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Processed By]" Member="Processed_By" Type="System.String" DbType="VarChar(303)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TransactionViewAll" Method="sp_TransactionViewAll">
    <ElementType Name="sp_TransactionViewAllResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Transaction Date]" Member="Transaction_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Transaction Event]" Member="Transaction_Event" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Processed By]" Member="Processed_By" Type="System.String" DbType="VarChar(303)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserActionReport" Method="sp_UserActionReport">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserBorrowAdd" Method="sp_UserBorrowAdd">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalBorrowedEquipments" Parameter="totalBorrowedEquipments" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserDelete" Method="sp_UserDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
  </Function>
  <Function Name="dbo.sp_UserEdit" Method="sp_UserEdit">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="FIRSTNAME" Parameter="fIRSTNAME" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="MIDDLENAME" Parameter="mIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LASTNAME" Parameter="lASTNAME" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CONTACT_NUMBER" Parameter="cONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USERTYPE_ID" Parameter="uSERTYPE_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserFirstLogin" Method="sp_UserFirstLogin">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserFirstLoginEdit" Method="sp_UserFirstLoginEdit">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISFIRSTLOGIN" Parameter="iSFIRSTLOGIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserID" Method="sp_UserID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserInsert" Method="sp_UserInsert">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="FIRSTNAME" Parameter="fIRSTNAME" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="MIDDLENAME" Parameter="mIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LASTNAME" Parameter="lASTNAME" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CONTACT_NUMBER" Parameter="cONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USERTYPE_ID" Parameter="uSERTYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISFIRSTLOGIN" Parameter="iSFIRSTLOGIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserLogin" Method="sp_UserLogin">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_UserLoginResult">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserLoginReport" Method="sp_UserLoginReport">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserReturnID" Method="sp_UserReturnID">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UserReturnIDResult">
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserSearch" Method="sp_UserSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_UserSearchResult">
      <Column Name="[General ID]" Member="General_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[User Type]" Member="User_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserSearchAdmin" Method="sp_UserSearchAdmin">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_UserSearchAdminResult">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserView" Method="sp_UserView">
    <ElementType Name="sp_UserViewResult">
      <Column Name="[General ID]" Member="General_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[User Type]" Member="User_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewAllFacilities" Method="sp_ViewAllFacilities">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="sp_ViewAllFacilitiesResult">
      <Column Name="FacilityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FacilityName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FacilityType" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FacilityRoomNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewAllRequest" Method="sp_ViewAllRequest">
    <ElementType Name="sp_ViewAllRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewApprovedRequest" Method="sp_ViewApprovedRequest">
    <ElementType Name="sp_ViewApprovedRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBorrowedEquipment" Method="sp_ViewBorrowedEquipment">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ViewBorrowedEquipmentResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Returned?]" Member="Returned_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBorrowStatistics" Method="sp_ViewBorrowStatistics">
    <ElementType Name="sp_ViewBorrowStatisticsResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="VarChar(302)" CanBeNull="true" />
      <Column Name="TotalBorrowedEquipments" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewDeniedRequest" Method="sp_ViewDeniedRequest">
    <ElementType Name="sp_ViewDeniedRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewDeployedEquipmentsFacilityID" Method="sp_ViewDeployedEquipmentsFacilityID">
    <Parameter Name="FacilityID" Parameter="facilityID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ViewDeployedEquipmentsFacilityIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Returned?]" Member="Returned_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewDeployedEquipmentsTransactionID" Method="sp_ViewDeployedEquipmentsTransactionID">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ViewDeployedEquipmentsTransactionIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Returned?]" Member="Returned_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewOpenRequest" Method="sp_ViewOpenRequest">
    <ElementType Name="sp_ViewOpenRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewPendingRequest" Method="sp_ViewPendingRequest">
    <ElementType Name="sp_ViewPendingRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewReservedEquipment" Method="sp_ViewReservedEquipment">
    <Parameter Name="TransactionID" Parameter="transactionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ViewReservedEquipmentResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>