#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANS_SEIS_TV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ANS_SEIS_TV")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEQUIPMENT_DESIGNATION(EQUIPMENT_DESIGNATION instance);
    partial void UpdateEQUIPMENT_DESIGNATION(EQUIPMENT_DESIGNATION instance);
    partial void DeleteEQUIPMENT_DESIGNATION(EQUIPMENT_DESIGNATION instance);
    partial void InsertTBLEQEUIPMENTTYPE(TBLEQEUIPMENTTYPE instance);
    partial void UpdateTBLEQEUIPMENTTYPE(TBLEQEUIPMENTTYPE instance);
    partial void DeleteTBLEQEUIPMENTTYPE(TBLEQEUIPMENTTYPE instance);
    partial void InsertTBLEQUIPMENTDETAIL(TBLEQUIPMENTDETAIL instance);
    partial void UpdateTBLEQUIPMENTDETAIL(TBLEQUIPMENTDETAIL instance);
    partial void DeleteTBLEQUIPMENTDETAIL(TBLEQUIPMENTDETAIL instance);
    partial void InsertTBLSTUDENTDETAIL(TBLSTUDENTDETAIL instance);
    partial void UpdateTBLSTUDENTDETAIL(TBLSTUDENTDETAIL instance);
    partial void DeleteTBLSTUDENTDETAIL(TBLSTUDENTDETAIL instance);
    partial void InsertTBLUSERACTIONREPORT(TBLUSERACTIONREPORT instance);
    partial void UpdateTBLUSERACTIONREPORT(TBLUSERACTIONREPORT instance);
    partial void DeleteTBLUSERACTIONREPORT(TBLUSERACTIONREPORT instance);
    partial void InsertTBLUSERDETAIL(TBLUSERDETAIL instance);
    partial void UpdateTBLUSERDETAIL(TBLUSERDETAIL instance);
    partial void DeleteTBLUSERDETAIL(TBLUSERDETAIL instance);
    partial void InsertTBLUSERLOGINREPORT(TBLUSERLOGINREPORT instance);
    partial void UpdateTBLUSERLOGINREPORT(TBLUSERLOGINREPORT instance);
    partial void DeleteTBLUSERLOGINREPORT(TBLUSERLOGINREPORT instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ANS_SEIS_TV.Properties.Settings.Default.ANS_SEIS_TVConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EQUIPMENT_DESIGNATION> EQUIPMENT_DESIGNATIONs
		{
			get
			{
				return this.GetTable<EQUIPMENT_DESIGNATION>();
			}
		}
		
		public System.Data.Linq.Table<USERTYPE> USERTYPEs
		{
			get
			{
				return this.GetTable<USERTYPE>();
			}
		}
		
		public System.Data.Linq.Table<REQUESTSTATUS> REQUESTSTATUS
		{
			get
			{
				return this.GetTable<REQUESTSTATUS>();
			}
		}
		
		public System.Data.Linq.Table<TBLEQEUIPMENTTYPE> TBLEQEUIPMENTTYPEs
		{
			get
			{
				return this.GetTable<TBLEQEUIPMENTTYPE>();
			}
		}
		
		public System.Data.Linq.Table<TBLEQUIPMENTDETAIL> TBLEQUIPMENTDETAILs
		{
			get
			{
				return this.GetTable<TBLEQUIPMENTDETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TBLREQUESTREPLY> TBLREQUESTREPLies
		{
			get
			{
				return this.GetTable<TBLREQUESTREPLY>();
			}
		}
		
		public System.Data.Linq.Table<TBLREQUESTTABLE> TBLREQUESTTABLEs
		{
			get
			{
				return this.GetTable<TBLREQUESTTABLE>();
			}
		}
		
		public System.Data.Linq.Table<TBLSTUDENTDETAIL> TBLSTUDENTDETAILs
		{
			get
			{
				return this.GetTable<TBLSTUDENTDETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TBLUSERACTIONREPORT> TBLUSERACTIONREPORTs
		{
			get
			{
				return this.GetTable<TBLUSERACTIONREPORT>();
			}
		}
		
		public System.Data.Linq.Table<TBLUSERDETAIL> TBLUSERDETAILs
		{
			get
			{
				return this.GetTable<TBLUSERDETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TBLUSERLOGINREPORT> TBLUSERLOGINREPORTs
		{
			get
			{
				return this.GetTable<TBLUSERLOGINREPORT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentBorrowableView")]
		public ISingleResult<sp_EquipmentBorrowableViewResult> sp_EquipmentBorrowableView([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<sp_EquipmentBorrowableViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewPendingRequest")]
		public ISingleResult<sp_ViewPendingRequestResult> sp_ViewPendingRequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewPendingRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentDelete")]
		public int sp_EquipmentDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_ID", DbType="Int")] System.Nullable<int> eQUIPMENT_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eQUIPMENT_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentEdit")]
		public int sp_EquipmentEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_ID", DbType="Int")] System.Nullable<int> eQUIPMENT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQBARCODE", DbType="VarChar(100)")] string eQBARCODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_NAME", DbType="VarChar(200)")] string eQUIPMENT_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_DESCRIPTION", DbType="VarChar(100)")] string eQUIPMENT_DESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_TYPE_ID", DbType="Int")] System.Nullable<int> eQUIPMENT_TYPE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_QUANTITY", DbType="Int")] System.Nullable<int> eQUIPMENT_QUANTITY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eQUIPMENT_ID, eQBARCODE, eQUIPMENT_NAME, eQUIPMENT_DESCRIPTION, eQUIPMENT_TYPE_ID, eQUIPMENT_QUANTITY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentID")]
		public int sp_EquipmentID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentQuantityEdit")]
		public int sp_EquipmentQuantityEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_ID", DbType="Int")] System.Nullable<int> eQUIPMENT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_QUANTITY", DbType="Int")] System.Nullable<int> eQUIPMENT_QUANTITY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eQUIPMENT_ID, eQUIPMENT_QUANTITY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentRegister")]
		public int sp_EquipmentRegister([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQBARCODE", DbType="VarChar(100)")] string eQBARCODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_NAME", DbType="VarChar(200)")] string eQUIPMENT_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_DESCRIPTION", DbType="VarChar(100)")] string eQUIPMENT_DESCRIPTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_TYPE_ID", DbType="Int")] System.Nullable<int> eQUIPMENT_TYPE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EQUIPMENT_QUANTITY", DbType="Int")] System.Nullable<int> eQUIPMENT_QUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBORROWABLE", DbType="Int")] System.Nullable<int> iSBORROWABLE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eQBARCODE, eQUIPMENT_NAME, eQUIPMENT_DESCRIPTION, eQUIPMENT_TYPE_ID, eQUIPMENT_QUANTITY, iSBORROWABLE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EquipmentView")]
		public ISingleResult<sp_EquipmentViewResult> sp_EquipmentView([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<sp_EquipmentViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_NewRequest")]
		public int sp_NewRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENID", DbType="Int")] System.Nullable<int> gENID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUESTHEADER", DbType="VarChar(100)")] string rEQUESTHEADER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUESTCONTENT", DbType="NVarChar(MAX)")] string rEQUESTCONTENT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATEREQUESTED", DbType="DateTime")] System.Nullable<System.DateTime> dATEREQUESTED, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REQUESTSTATUSID", DbType="Int")] System.Nullable<int> rEQUESTSTATUSID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISOPENED", DbType="Int")] System.Nullable<int> iSOPENED)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gENID, rEQUESTHEADER, rEQUESTCONTENT, dATEREQUESTED, rEQUESTSTATUSID, iSOPENED);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RequestReplied")]
		public int sp_RequestReplied([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="Int")] System.Nullable<int> requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RequestReply")]
		public int sp_RequestReply([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENID", DbType="Int")] System.Nullable<int> gENID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REPLYCONTENT", DbType="NVarChar(MAX)")] string rEPLYCONTENT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gENID, rEPLYCONTENT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_RequestViewed")]
		public int sp_RequestViewed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="Int")] System.Nullable<int> requestID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), requestID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_StudentInsert")]
		public int sp_StudentInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="VarChar(200)")] string nAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, pASSWORD, nAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_StudentSearch")]
		public ISingleResult<sp_StudentSearchResult> sp_StudentSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<sp_StudentSearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_StudentView")]
		public ISingleResult<sp_StudentViewResult> sp_StudentView()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_StudentViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserActionReport")]
		public int sp_UserActionReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="VarChar(50)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Timestamp", DbType="DateTime")] System.Nullable<System.DateTime> timestamp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, action, timestamp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserDelete")]
		public int sp_UserDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserEdit")]
		public int sp_UserEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENID", DbType="Int")] System.Nullable<int> gENID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRSTNAME", DbType="VarChar(150)")] string fIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIDDLENAME", DbType="VarChar(50)")] string mIDDLENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LASTNAME", DbType="VarChar(100)")] string lASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACT_NUMBER", DbType="VarChar(20)")] string cONTACT_NUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_QUESTION", DbType="VarChar(MAX)")] string sECURITY_QUESTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_ANSWER", DbType="VarChar(MAX)")] string sECURITY_ANSWER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERTYPE_ID", DbType="Int")] System.Nullable<int> uSERTYPE_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gENID, iD, uSERNAME, pASSWORD, fIRSTNAME, mIDDLENAME, lASTNAME, cONTACT_NUMBER, sECURITY_QUESTION, sECURITY_ANSWER, uSERTYPE_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserFirstLogin")]
		public int sp_UserFirstLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_QUESTION", DbType="VarChar(MAX)")] string sECURITY_QUESTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_ANSWER", DbType="VarChar(MAX)")] string sECURITY_ANSWER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, pASSWORD, sECURITY_QUESTION, sECURITY_ANSWER);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserFirstLoginEdit")]
		public int sp_UserFirstLoginEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENID", DbType="Int")] System.Nullable<int> gENID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISFIRSTLOGIN", DbType="Int")] System.Nullable<int> iSFIRSTLOGIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gENID, iSFIRSTLOGIN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserID")]
		public int sp_UserID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserInsert")]
		public int sp_UserInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(MAX)")] string pASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRSTNAME", DbType="VarChar(150)")] string fIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIDDLENAME", DbType="VarChar(50)")] string mIDDLENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LASTNAME", DbType="VarChar(100)")] string lASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTACT_NUMBER", DbType="VarChar(20)")] string cONTACT_NUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_QUESTION", DbType="VarChar(MAX)")] string sECURITY_QUESTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECURITY_ANSWER", DbType="VarChar(MAX)")] string sECURITY_ANSWER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERTYPE_ID", DbType="Int")] System.Nullable<int> uSERTYPE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISFIRSTLOGIN", DbType="Int")] System.Nullable<int> iSFIRSTLOGIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, uSERNAME, pASSWORD, fIRSTNAME, mIDDLENAME, lASTNAME, cONTACT_NUMBER, sECURITY_QUESTION, sECURITY_ANSWER, uSERTYPE_ID, iSFIRSTLOGIN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserLogin")]
		public ISingleResult<sp_UserLoginResult> sp_UserLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD", DbType="VarChar(MAX)")] string pASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, pASSWORD);
			return ((ISingleResult<sp_UserLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserLoginReport")]
		public int sp_UserLoginReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="VarChar(100)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Timestamp", DbType="DateTime")] System.Nullable<System.DateTime> timestamp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, password, action, timestamp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserReturnID")]
		public ISingleResult<sp_UserReturnIDResult> sp_UserReturnID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(50)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GENID", DbType="Int")] System.Nullable<int> gENID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, gENID);
			return ((ISingleResult<sp_UserReturnIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserSearch")]
		public ISingleResult<sp_UserSearchResult> sp_UserSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<sp_UserSearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserSearchAdmin")]
		public ISingleResult<sp_UserSearchAdminResult> sp_UserSearchAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="VarChar(50)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<sp_UserSearchAdminResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserView")]
		public ISingleResult<sp_UserViewResult> sp_UserView()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_UserViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewAllRequest")]
		public ISingleResult<sp_ViewAllRequestResult> sp_ViewAllRequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewAllRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewClosedRequest")]
		public ISingleResult<sp_ViewClosedRequestResult> sp_ViewClosedRequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewClosedRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ViewOpenRequest")]
		public ISingleResult<sp_ViewOpenRequestResult> sp_ViewOpenRequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ViewOpenRequestResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EQUIPMENT_DESIGNATION")]
	public partial class EQUIPMENT_DESIGNATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EQ_DESIGNATION_ID;
		
		private string _ID;
		
		private string _EQBARCODE;
		
		private System.Nullable<System.DateTime> _DATE_DESIGNATED;
		
		private System.Nullable<System.DateTime> _DATE_RETURNED;
		
		private string _DESIGNATION_STATUS;
		
		private EntityRef<TBLEQUIPMENTDETAIL> _TBLEQUIPMENTDETAIL;
		
		private EntityRef<TBLUSERDETAIL> _TBLUSERDETAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEQ_DESIGNATION_IDChanging(int value);
    partial void OnEQ_DESIGNATION_IDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnEQBARCODEChanging(string value);
    partial void OnEQBARCODEChanged();
    partial void OnDATE_DESIGNATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_DESIGNATEDChanged();
    partial void OnDATE_RETURNEDChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_RETURNEDChanged();
    partial void OnDESIGNATION_STATUSChanging(string value);
    partial void OnDESIGNATION_STATUSChanged();
    #endregion
		
		public EQUIPMENT_DESIGNATION()
		{
			this._TBLEQUIPMENTDETAIL = default(EntityRef<TBLEQUIPMENTDETAIL>);
			this._TBLUSERDETAIL = default(EntityRef<TBLUSERDETAIL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQ_DESIGNATION_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EQ_DESIGNATION_ID
		{
			get
			{
				return this._EQ_DESIGNATION_ID;
			}
			set
			{
				if ((this._EQ_DESIGNATION_ID != value))
				{
					this.OnEQ_DESIGNATION_IDChanging(value);
					this.SendPropertyChanging();
					this._EQ_DESIGNATION_ID = value;
					this.SendPropertyChanged("EQ_DESIGNATION_ID");
					this.OnEQ_DESIGNATION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TBLUSERDETAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQBARCODE", DbType="VarChar(100)")]
		public string EQBARCODE
		{
			get
			{
				return this._EQBARCODE;
			}
			set
			{
				if ((this._EQBARCODE != value))
				{
					if (this._TBLEQUIPMENTDETAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEQBARCODEChanging(value);
					this.SendPropertyChanging();
					this._EQBARCODE = value;
					this.SendPropertyChanged("EQBARCODE");
					this.OnEQBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_DESIGNATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_DESIGNATED
		{
			get
			{
				return this._DATE_DESIGNATED;
			}
			set
			{
				if ((this._DATE_DESIGNATED != value))
				{
					this.OnDATE_DESIGNATEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_DESIGNATED = value;
					this.SendPropertyChanged("DATE_DESIGNATED");
					this.OnDATE_DESIGNATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_RETURNED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_RETURNED
		{
			get
			{
				return this._DATE_RETURNED;
			}
			set
			{
				if ((this._DATE_RETURNED != value))
				{
					this.OnDATE_RETURNEDChanging(value);
					this.SendPropertyChanging();
					this._DATE_RETURNED = value;
					this.SendPropertyChanged("DATE_RETURNED");
					this.OnDATE_RETURNEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATION_STATUS", DbType="VarChar(50)")]
		public string DESIGNATION_STATUS
		{
			get
			{
				return this._DESIGNATION_STATUS;
			}
			set
			{
				if ((this._DESIGNATION_STATUS != value))
				{
					this.OnDESIGNATION_STATUSChanging(value);
					this.SendPropertyChanging();
					this._DESIGNATION_STATUS = value;
					this.SendPropertyChanged("DESIGNATION_STATUS");
					this.OnDESIGNATION_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLEQUIPMENTDETAIL_EQUIPMENT_DESIGNATION", Storage="_TBLEQUIPMENTDETAIL", ThisKey="EQBARCODE", OtherKey="EQBARCODE", IsForeignKey=true)]
		public TBLEQUIPMENTDETAIL TBLEQUIPMENTDETAIL
		{
			get
			{
				return this._TBLEQUIPMENTDETAIL.Entity;
			}
			set
			{
				TBLEQUIPMENTDETAIL previousValue = this._TBLEQUIPMENTDETAIL.Entity;
				if (((previousValue != value) 
							|| (this._TBLEQUIPMENTDETAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLEQUIPMENTDETAIL.Entity = null;
						previousValue.EQUIPMENT_DESIGNATIONs.Remove(this);
					}
					this._TBLEQUIPMENTDETAIL.Entity = value;
					if ((value != null))
					{
						value.EQUIPMENT_DESIGNATIONs.Add(this);
						this._EQBARCODE = value.EQBARCODE;
					}
					else
					{
						this._EQBARCODE = default(string);
					}
					this.SendPropertyChanged("TBLEQUIPMENTDETAIL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_EQUIPMENT_DESIGNATION", Storage="_TBLUSERDETAIL", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TBLUSERDETAIL TBLUSERDETAIL
		{
			get
			{
				return this._TBLUSERDETAIL.Entity;
			}
			set
			{
				TBLUSERDETAIL previousValue = this._TBLUSERDETAIL.Entity;
				if (((previousValue != value) 
							|| (this._TBLUSERDETAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLUSERDETAIL.Entity = null;
						previousValue.EQUIPMENT_DESIGNATIONs.Remove(this);
					}
					this._TBLUSERDETAIL.Entity = value;
					if ((value != null))
					{
						value.EQUIPMENT_DESIGNATIONs.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("TBLUSERDETAIL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERTYPE")]
	public partial class USERTYPE
	{
		
		private int _USERTYPE_ID;
		
		private string _USERTYPE_DESCRIPTION;
		
		public USERTYPE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERTYPE_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int USERTYPE_ID
		{
			get
			{
				return this._USERTYPE_ID;
			}
			set
			{
				if ((this._USERTYPE_ID != value))
				{
					this._USERTYPE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERTYPE_DESCRIPTION", DbType="VarChar(50)")]
		public string USERTYPE_DESCRIPTION
		{
			get
			{
				return this._USERTYPE_DESCRIPTION;
			}
			set
			{
				if ((this._USERTYPE_DESCRIPTION != value))
				{
					this._USERTYPE_DESCRIPTION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REQUESTSTATUS")]
	public partial class REQUESTSTATUS
	{
		
		private int _REQUESTSTATUSID;
		
		private string _STATUSDESCRIPTION;
		
		public REQUESTSTATUS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTSTATUSID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int REQUESTSTATUSID
		{
			get
			{
				return this._REQUESTSTATUSID;
			}
			set
			{
				if ((this._REQUESTSTATUSID != value))
				{
					this._REQUESTSTATUSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSDESCRIPTION", DbType="VarChar(15)")]
		public string STATUSDESCRIPTION
		{
			get
			{
				return this._STATUSDESCRIPTION;
			}
			set
			{
				if ((this._STATUSDESCRIPTION != value))
				{
					this._STATUSDESCRIPTION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLEQEUIPMENTTYPE")]
	public partial class TBLEQEUIPMENTTYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EQUIPMENT_TYPE_ID;
		
		private string _EQUIPMENT_TYPE_DESCRIPTION;
		
		private EntitySet<TBLEQUIPMENTDETAIL> _TBLEQUIPMENTDETAILs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEQUIPMENT_TYPE_IDChanging(int value);
    partial void OnEQUIPMENT_TYPE_IDChanged();
    partial void OnEQUIPMENT_TYPE_DESCRIPTIONChanging(string value);
    partial void OnEQUIPMENT_TYPE_DESCRIPTIONChanged();
    #endregion
		
		public TBLEQEUIPMENTTYPE()
		{
			this._TBLEQUIPMENTDETAILs = new EntitySet<TBLEQUIPMENTDETAIL>(new Action<TBLEQUIPMENTDETAIL>(this.attach_TBLEQUIPMENTDETAILs), new Action<TBLEQUIPMENTDETAIL>(this.detach_TBLEQUIPMENTDETAILs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_TYPE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EQUIPMENT_TYPE_ID
		{
			get
			{
				return this._EQUIPMENT_TYPE_ID;
			}
			set
			{
				if ((this._EQUIPMENT_TYPE_ID != value))
				{
					this.OnEQUIPMENT_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_TYPE_ID = value;
					this.SendPropertyChanged("EQUIPMENT_TYPE_ID");
					this.OnEQUIPMENT_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_TYPE_DESCRIPTION", DbType="VarChar(100)")]
		public string EQUIPMENT_TYPE_DESCRIPTION
		{
			get
			{
				return this._EQUIPMENT_TYPE_DESCRIPTION;
			}
			set
			{
				if ((this._EQUIPMENT_TYPE_DESCRIPTION != value))
				{
					this.OnEQUIPMENT_TYPE_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_TYPE_DESCRIPTION = value;
					this.SendPropertyChanged("EQUIPMENT_TYPE_DESCRIPTION");
					this.OnEQUIPMENT_TYPE_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLEQEUIPMENTTYPE_TBLEQUIPMENTDETAIL", Storage="_TBLEQUIPMENTDETAILs", ThisKey="EQUIPMENT_TYPE_ID", OtherKey="EQUIPMENT_TYPE_ID")]
		public EntitySet<TBLEQUIPMENTDETAIL> TBLEQUIPMENTDETAILs
		{
			get
			{
				return this._TBLEQUIPMENTDETAILs;
			}
			set
			{
				this._TBLEQUIPMENTDETAILs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBLEQUIPMENTDETAILs(TBLEQUIPMENTDETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLEQEUIPMENTTYPE = this;
		}
		
		private void detach_TBLEQUIPMENTDETAILs(TBLEQUIPMENTDETAIL entity)
		{
			this.SendPropertyChanging();
			entity.TBLEQEUIPMENTTYPE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLEQUIPMENTDETAILS")]
	public partial class TBLEQUIPMENTDETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EQUIPMENT_ID;
		
		private string _EQBARCODE;
		
		private string _EQUIPMENT_NAME;
		
		private string _EQUIPMENT_DESCRIPTION;
		
		private System.Nullable<int> _EQUIPMENT_TYPE_ID;
		
		private System.Nullable<int> _EQUIPMENT_QUANTITY;
		
		private System.Nullable<int> _ISBORROWABLE;
		
		private EntitySet<EQUIPMENT_DESIGNATION> _EQUIPMENT_DESIGNATIONs;
		
		private EntityRef<TBLEQEUIPMENTTYPE> _TBLEQEUIPMENTTYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEQUIPMENT_IDChanging(int value);
    partial void OnEQUIPMENT_IDChanged();
    partial void OnEQBARCODEChanging(string value);
    partial void OnEQBARCODEChanged();
    partial void OnEQUIPMENT_NAMEChanging(string value);
    partial void OnEQUIPMENT_NAMEChanged();
    partial void OnEQUIPMENT_DESCRIPTIONChanging(string value);
    partial void OnEQUIPMENT_DESCRIPTIONChanged();
    partial void OnEQUIPMENT_TYPE_IDChanging(System.Nullable<int> value);
    partial void OnEQUIPMENT_TYPE_IDChanged();
    partial void OnEQUIPMENT_QUANTITYChanging(System.Nullable<int> value);
    partial void OnEQUIPMENT_QUANTITYChanged();
    partial void OnISBORROWABLEChanging(System.Nullable<int> value);
    partial void OnISBORROWABLEChanged();
    #endregion
		
		public TBLEQUIPMENTDETAIL()
		{
			this._EQUIPMENT_DESIGNATIONs = new EntitySet<EQUIPMENT_DESIGNATION>(new Action<EQUIPMENT_DESIGNATION>(this.attach_EQUIPMENT_DESIGNATIONs), new Action<EQUIPMENT_DESIGNATION>(this.detach_EQUIPMENT_DESIGNATIONs));
			this._TBLEQEUIPMENTTYPE = default(EntityRef<TBLEQEUIPMENTTYPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int EQUIPMENT_ID
		{
			get
			{
				return this._EQUIPMENT_ID;
			}
			set
			{
				if ((this._EQUIPMENT_ID != value))
				{
					this.OnEQUIPMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_ID = value;
					this.SendPropertyChanged("EQUIPMENT_ID");
					this.OnEQUIPMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQBARCODE", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EQBARCODE
		{
			get
			{
				return this._EQBARCODE;
			}
			set
			{
				if ((this._EQBARCODE != value))
				{
					this.OnEQBARCODEChanging(value);
					this.SendPropertyChanging();
					this._EQBARCODE = value;
					this.SendPropertyChanged("EQBARCODE");
					this.OnEQBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_NAME", DbType="VarChar(200)")]
		public string EQUIPMENT_NAME
		{
			get
			{
				return this._EQUIPMENT_NAME;
			}
			set
			{
				if ((this._EQUIPMENT_NAME != value))
				{
					this.OnEQUIPMENT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_NAME = value;
					this.SendPropertyChanged("EQUIPMENT_NAME");
					this.OnEQUIPMENT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_DESCRIPTION", DbType="VarChar(100)")]
		public string EQUIPMENT_DESCRIPTION
		{
			get
			{
				return this._EQUIPMENT_DESCRIPTION;
			}
			set
			{
				if ((this._EQUIPMENT_DESCRIPTION != value))
				{
					this.OnEQUIPMENT_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_DESCRIPTION = value;
					this.SendPropertyChanged("EQUIPMENT_DESCRIPTION");
					this.OnEQUIPMENT_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_TYPE_ID", DbType="Int")]
		public System.Nullable<int> EQUIPMENT_TYPE_ID
		{
			get
			{
				return this._EQUIPMENT_TYPE_ID;
			}
			set
			{
				if ((this._EQUIPMENT_TYPE_ID != value))
				{
					if (this._TBLEQEUIPMENTTYPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEQUIPMENT_TYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_TYPE_ID = value;
					this.SendPropertyChanged("EQUIPMENT_TYPE_ID");
					this.OnEQUIPMENT_TYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_QUANTITY", DbType="Int")]
		public System.Nullable<int> EQUIPMENT_QUANTITY
		{
			get
			{
				return this._EQUIPMENT_QUANTITY;
			}
			set
			{
				if ((this._EQUIPMENT_QUANTITY != value))
				{
					this.OnEQUIPMENT_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENT_QUANTITY = value;
					this.SendPropertyChanged("EQUIPMENT_QUANTITY");
					this.OnEQUIPMENT_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBORROWABLE", DbType="Int")]
		public System.Nullable<int> ISBORROWABLE
		{
			get
			{
				return this._ISBORROWABLE;
			}
			set
			{
				if ((this._ISBORROWABLE != value))
				{
					this.OnISBORROWABLEChanging(value);
					this.SendPropertyChanging();
					this._ISBORROWABLE = value;
					this.SendPropertyChanged("ISBORROWABLE");
					this.OnISBORROWABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLEQUIPMENTDETAIL_EQUIPMENT_DESIGNATION", Storage="_EQUIPMENT_DESIGNATIONs", ThisKey="EQBARCODE", OtherKey="EQBARCODE")]
		public EntitySet<EQUIPMENT_DESIGNATION> EQUIPMENT_DESIGNATIONs
		{
			get
			{
				return this._EQUIPMENT_DESIGNATIONs;
			}
			set
			{
				this._EQUIPMENT_DESIGNATIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLEQEUIPMENTTYPE_TBLEQUIPMENTDETAIL", Storage="_TBLEQEUIPMENTTYPE", ThisKey="EQUIPMENT_TYPE_ID", OtherKey="EQUIPMENT_TYPE_ID", IsForeignKey=true)]
		public TBLEQEUIPMENTTYPE TBLEQEUIPMENTTYPE
		{
			get
			{
				return this._TBLEQEUIPMENTTYPE.Entity;
			}
			set
			{
				TBLEQEUIPMENTTYPE previousValue = this._TBLEQEUIPMENTTYPE.Entity;
				if (((previousValue != value) 
							|| (this._TBLEQEUIPMENTTYPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLEQEUIPMENTTYPE.Entity = null;
						previousValue.TBLEQUIPMENTDETAILs.Remove(this);
					}
					this._TBLEQEUIPMENTTYPE.Entity = value;
					if ((value != null))
					{
						value.TBLEQUIPMENTDETAILs.Add(this);
						this._EQUIPMENT_TYPE_ID = value.EQUIPMENT_TYPE_ID;
					}
					else
					{
						this._EQUIPMENT_TYPE_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBLEQEUIPMENTTYPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EQUIPMENT_DESIGNATIONs(EQUIPMENT_DESIGNATION entity)
		{
			this.SendPropertyChanging();
			entity.TBLEQUIPMENTDETAIL = this;
		}
		
		private void detach_EQUIPMENT_DESIGNATIONs(EQUIPMENT_DESIGNATION entity)
		{
			this.SendPropertyChanging();
			entity.TBLEQUIPMENTDETAIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLREQUESTREPLY")]
	public partial class TBLREQUESTREPLY
	{
		
		private int _ReplyID;
		
		private System.Nullable<int> _GENID;
		
		private string _ReplyContent;
		
		public TBLREQUESTREPLY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ReplyID
		{
			get
			{
				return this._ReplyID;
			}
			set
			{
				if ((this._ReplyID != value))
				{
					this._ReplyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", DbType="Int")]
		public System.Nullable<int> GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this._GENID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyContent", DbType="NVarChar(MAX)")]
		public string ReplyContent
		{
			get
			{
				return this._ReplyContent;
			}
			set
			{
				if ((this._ReplyContent != value))
				{
					this._ReplyContent = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLREQUESTTABLE")]
	public partial class TBLREQUESTTABLE
	{
		
		private int _REQUESTID;
		
		private System.Nullable<int> _GENID;
		
		private string _REQUESTHEADER;
		
		private string _REQUESTCONTENT;
		
		private System.Nullable<System.DateTime> _DATEREQUESTED;
		
		private System.Nullable<int> _REQUESTSTATUSID;
		
		private System.Nullable<int> _ISOPENED;
		
		public TBLREQUESTTABLE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int REQUESTID
		{
			get
			{
				return this._REQUESTID;
			}
			set
			{
				if ((this._REQUESTID != value))
				{
					this._REQUESTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", DbType="Int")]
		public System.Nullable<int> GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this._GENID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTHEADER", DbType="VarChar(100)")]
		public string REQUESTHEADER
		{
			get
			{
				return this._REQUESTHEADER;
			}
			set
			{
				if ((this._REQUESTHEADER != value))
				{
					this._REQUESTHEADER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTCONTENT", DbType="NVarChar(MAX)")]
		public string REQUESTCONTENT
		{
			get
			{
				return this._REQUESTCONTENT;
			}
			set
			{
				if ((this._REQUESTCONTENT != value))
				{
					this._REQUESTCONTENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATEREQUESTED", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATEREQUESTED
		{
			get
			{
				return this._DATEREQUESTED;
			}
			set
			{
				if ((this._DATEREQUESTED != value))
				{
					this._DATEREQUESTED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUESTSTATUSID", DbType="Int")]
		public System.Nullable<int> REQUESTSTATUSID
		{
			get
			{
				return this._REQUESTSTATUSID;
			}
			set
			{
				if ((this._REQUESTSTATUSID != value))
				{
					this._REQUESTSTATUSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISOPENED", DbType="Int")]
		public System.Nullable<int> ISOPENED
		{
			get
			{
				return this._ISOPENED;
			}
			set
			{
				if ((this._ISOPENED != value))
				{
					this._ISOPENED = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLSTUDENTDETAILS")]
	public partial class TBLSTUDENTDETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GENID;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGENIDChanging(int value);
    partial void OnGENIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public TBLSTUDENTDETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this.OnGENIDChanging(value);
					this.SendPropertyChanging();
					this._GENID = value;
					this.SendPropertyChanged("GENID");
					this.OnGENIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(MAX)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLUSERACTIONREPORT")]
	public partial class TBLUSERACTIONREPORT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ActionID;
		
		private string _ID;
		
		private string _Action;
		
		private System.Nullable<System.DateTime> _Timestamp;
		
		private EntityRef<TBLUSERDETAIL> _TBLUSERDETAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActionIDChanging(int value);
    partial void OnActionIDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestampChanged();
    #endregion
		
		public TBLUSERACTIONREPORT()
		{
			this._TBLUSERDETAIL = default(EntityRef<TBLUSERDETAIL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ActionID
		{
			get
			{
				return this._ActionID;
			}
			set
			{
				if ((this._ActionID != value))
				{
					this.OnActionIDChanging(value);
					this.SendPropertyChanging();
					this._ActionID = value;
					this.SendPropertyChanged("ActionID");
					this.OnActionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TBLUSERDETAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_TBLUSERACTIONREPORT", Storage="_TBLUSERDETAIL", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TBLUSERDETAIL TBLUSERDETAIL
		{
			get
			{
				return this._TBLUSERDETAIL.Entity;
			}
			set
			{
				TBLUSERDETAIL previousValue = this._TBLUSERDETAIL.Entity;
				if (((previousValue != value) 
							|| (this._TBLUSERDETAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLUSERDETAIL.Entity = null;
						previousValue.TBLUSERACTIONREPORTs.Remove(this);
					}
					this._TBLUSERDETAIL.Entity = value;
					if ((value != null))
					{
						value.TBLUSERACTIONREPORTs.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("TBLUSERDETAIL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLUSERDETAILS")]
	public partial class TBLUSERDETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GENID;
		
		private string _ID;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private string _FIRSTNAME;
		
		private string _MIDDLENAME;
		
		private string _LASTNAME;
		
		private string _CONTACT_NUMBER;
		
		private string _SECURITY_QUESTION;
		
		private string _SECURITY_ANSWER;
		
		private System.Nullable<int> _USERTYPE_ID;
		
		private System.Nullable<int> _ISFIRSTLOGIN;
		
		private EntitySet<EQUIPMENT_DESIGNATION> _EQUIPMENT_DESIGNATIONs;
		
		private EntitySet<TBLUSERACTIONREPORT> _TBLUSERACTIONREPORTs;
		
		private EntitySet<TBLUSERLOGINREPORT> _TBLUSERLOGINREPORTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGENIDChanging(int value);
    partial void OnGENIDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnFIRSTNAMEChanging(string value);
    partial void OnFIRSTNAMEChanged();
    partial void OnMIDDLENAMEChanging(string value);
    partial void OnMIDDLENAMEChanged();
    partial void OnLASTNAMEChanging(string value);
    partial void OnLASTNAMEChanged();
    partial void OnCONTACT_NUMBERChanging(string value);
    partial void OnCONTACT_NUMBERChanged();
    partial void OnSECURITY_QUESTIONChanging(string value);
    partial void OnSECURITY_QUESTIONChanged();
    partial void OnSECURITY_ANSWERChanging(string value);
    partial void OnSECURITY_ANSWERChanged();
    partial void OnUSERTYPE_IDChanging(System.Nullable<int> value);
    partial void OnUSERTYPE_IDChanged();
    partial void OnISFIRSTLOGINChanging(System.Nullable<int> value);
    partial void OnISFIRSTLOGINChanged();
    #endregion
		
		public TBLUSERDETAIL()
		{
			this._EQUIPMENT_DESIGNATIONs = new EntitySet<EQUIPMENT_DESIGNATION>(new Action<EQUIPMENT_DESIGNATION>(this.attach_EQUIPMENT_DESIGNATIONs), new Action<EQUIPMENT_DESIGNATION>(this.detach_EQUIPMENT_DESIGNATIONs));
			this._TBLUSERACTIONREPORTs = new EntitySet<TBLUSERACTIONREPORT>(new Action<TBLUSERACTIONREPORT>(this.attach_TBLUSERACTIONREPORTs), new Action<TBLUSERACTIONREPORT>(this.detach_TBLUSERACTIONREPORTs));
			this._TBLUSERLOGINREPORTs = new EntitySet<TBLUSERLOGINREPORT>(new Action<TBLUSERLOGINREPORT>(this.attach_TBLUSERLOGINREPORTs), new Action<TBLUSERLOGINREPORT>(this.detach_TBLUSERLOGINREPORTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this.OnGENIDChanging(value);
					this.SendPropertyChanging();
					this._GENID = value;
					this.SendPropertyChanged("GENID");
					this.OnGENIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(MAX)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRSTNAME", DbType="VarChar(150)")]
		public string FIRSTNAME
		{
			get
			{
				return this._FIRSTNAME;
			}
			set
			{
				if ((this._FIRSTNAME != value))
				{
					this.OnFIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRSTNAME = value;
					this.SendPropertyChanged("FIRSTNAME");
					this.OnFIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIDDLENAME", DbType="VarChar(50)")]
		public string MIDDLENAME
		{
			get
			{
				return this._MIDDLENAME;
			}
			set
			{
				if ((this._MIDDLENAME != value))
				{
					this.OnMIDDLENAMEChanging(value);
					this.SendPropertyChanging();
					this._MIDDLENAME = value;
					this.SendPropertyChanged("MIDDLENAME");
					this.OnMIDDLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTNAME", DbType="VarChar(100)")]
		public string LASTNAME
		{
			get
			{
				return this._LASTNAME;
			}
			set
			{
				if ((this._LASTNAME != value))
				{
					this.OnLASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._LASTNAME = value;
					this.SendPropertyChanged("LASTNAME");
					this.OnLASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_NUMBER", DbType="VarChar(20)")]
		public string CONTACT_NUMBER
		{
			get
			{
				return this._CONTACT_NUMBER;
			}
			set
			{
				if ((this._CONTACT_NUMBER != value))
				{
					this.OnCONTACT_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._CONTACT_NUMBER = value;
					this.SendPropertyChanged("CONTACT_NUMBER");
					this.OnCONTACT_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITY_QUESTION", DbType="VarChar(MAX)")]
		public string SECURITY_QUESTION
		{
			get
			{
				return this._SECURITY_QUESTION;
			}
			set
			{
				if ((this._SECURITY_QUESTION != value))
				{
					this.OnSECURITY_QUESTIONChanging(value);
					this.SendPropertyChanging();
					this._SECURITY_QUESTION = value;
					this.SendPropertyChanged("SECURITY_QUESTION");
					this.OnSECURITY_QUESTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECURITY_ANSWER", DbType="VarChar(MAX)")]
		public string SECURITY_ANSWER
		{
			get
			{
				return this._SECURITY_ANSWER;
			}
			set
			{
				if ((this._SECURITY_ANSWER != value))
				{
					this.OnSECURITY_ANSWERChanging(value);
					this.SendPropertyChanging();
					this._SECURITY_ANSWER = value;
					this.SendPropertyChanged("SECURITY_ANSWER");
					this.OnSECURITY_ANSWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERTYPE_ID", DbType="Int")]
		public System.Nullable<int> USERTYPE_ID
		{
			get
			{
				return this._USERTYPE_ID;
			}
			set
			{
				if ((this._USERTYPE_ID != value))
				{
					this.OnUSERTYPE_IDChanging(value);
					this.SendPropertyChanging();
					this._USERTYPE_ID = value;
					this.SendPropertyChanged("USERTYPE_ID");
					this.OnUSERTYPE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISFIRSTLOGIN", DbType="Int")]
		public System.Nullable<int> ISFIRSTLOGIN
		{
			get
			{
				return this._ISFIRSTLOGIN;
			}
			set
			{
				if ((this._ISFIRSTLOGIN != value))
				{
					this.OnISFIRSTLOGINChanging(value);
					this.SendPropertyChanging();
					this._ISFIRSTLOGIN = value;
					this.SendPropertyChanged("ISFIRSTLOGIN");
					this.OnISFIRSTLOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_EQUIPMENT_DESIGNATION", Storage="_EQUIPMENT_DESIGNATIONs", ThisKey="ID", OtherKey="ID")]
		public EntitySet<EQUIPMENT_DESIGNATION> EQUIPMENT_DESIGNATIONs
		{
			get
			{
				return this._EQUIPMENT_DESIGNATIONs;
			}
			set
			{
				this._EQUIPMENT_DESIGNATIONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_TBLUSERACTIONREPORT", Storage="_TBLUSERACTIONREPORTs", ThisKey="ID", OtherKey="ID")]
		public EntitySet<TBLUSERACTIONREPORT> TBLUSERACTIONREPORTs
		{
			get
			{
				return this._TBLUSERACTIONREPORTs;
			}
			set
			{
				this._TBLUSERACTIONREPORTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_TBLUSERLOGINREPORT", Storage="_TBLUSERLOGINREPORTs", ThisKey="ID", OtherKey="ID")]
		public EntitySet<TBLUSERLOGINREPORT> TBLUSERLOGINREPORTs
		{
			get
			{
				return this._TBLUSERLOGINREPORTs;
			}
			set
			{
				this._TBLUSERLOGINREPORTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EQUIPMENT_DESIGNATIONs(EQUIPMENT_DESIGNATION entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = this;
		}
		
		private void detach_EQUIPMENT_DESIGNATIONs(EQUIPMENT_DESIGNATION entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = null;
		}
		
		private void attach_TBLUSERACTIONREPORTs(TBLUSERACTIONREPORT entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = this;
		}
		
		private void detach_TBLUSERACTIONREPORTs(TBLUSERACTIONREPORT entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = null;
		}
		
		private void attach_TBLUSERLOGINREPORTs(TBLUSERLOGINREPORT entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = this;
		}
		
		private void detach_TBLUSERLOGINREPORTs(TBLUSERLOGINREPORT entity)
		{
			this.SendPropertyChanging();
			entity.TBLUSERDETAIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLUSERLOGINREPORT")]
	public partial class TBLUSERLOGINREPORT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoginID;
		
		private string _ID;
		
		private string _password;
		
		private string _Action;
		
		private System.Nullable<System.DateTime> _Timestamp;
		
		private EntityRef<TBLUSERDETAIL> _TBLUSERDETAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginIDChanging(int value);
    partial void OnLoginIDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestampChanged();
    #endregion
		
		public TBLUSERLOGINREPORT()
		{
			this._TBLUSERDETAIL = default(EntityRef<TBLUSERDETAIL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this.OnLoginIDChanging(value);
					this.SendPropertyChanging();
					this._LoginID = value;
					this.SendPropertyChanged("LoginID");
					this.OnLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TBLUSERDETAIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(100)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBLUSERDETAIL_TBLUSERLOGINREPORT", Storage="_TBLUSERDETAIL", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TBLUSERDETAIL TBLUSERDETAIL
		{
			get
			{
				return this._TBLUSERDETAIL.Entity;
			}
			set
			{
				TBLUSERDETAIL previousValue = this._TBLUSERDETAIL.Entity;
				if (((previousValue != value) 
							|| (this._TBLUSERDETAIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBLUSERDETAIL.Entity = null;
						previousValue.TBLUSERLOGINREPORTs.Remove(this);
					}
					this._TBLUSERDETAIL.Entity = value;
					if ((value != null))
					{
						value.TBLUSERLOGINREPORTs.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("TBLUSERDETAIL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_EquipmentBorrowableViewResult
	{
		
		private string _Equipment_Barcode;
		
		private string _Name;
		
		private string _Description;
		
		private string _EQUIPMENT_TYPE_DESCRIPTION;
		
		public sp_EquipmentBorrowableViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Equipment Barcode]", Storage="_Equipment_Barcode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Equipment_Barcode
		{
			get
			{
				return this._Equipment_Barcode;
			}
			set
			{
				if ((this._Equipment_Barcode != value))
				{
					this._Equipment_Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_TYPE_DESCRIPTION", DbType="VarChar(100)")]
		public string EQUIPMENT_TYPE_DESCRIPTION
		{
			get
			{
				return this._EQUIPMENT_TYPE_DESCRIPTION;
			}
			set
			{
				if ((this._EQUIPMENT_TYPE_DESCRIPTION != value))
				{
					this._EQUIPMENT_TYPE_DESCRIPTION = value;
				}
			}
		}
	}
	
	public partial class sp_ViewPendingRequestResult
	{
		
		private int _Request_ID;
		
		private string _Username;
		
		private string _Request_Header;
		
		private System.Nullable<System.DateTime> _Date_Requested;
		
		private string _Status;
		
		public sp_ViewPendingRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request ID]", Storage="_Request_ID", DbType="Int NOT NULL")]
		public int Request_ID
		{
			get
			{
				return this._Request_ID;
			}
			set
			{
				if ((this._Request_ID != value))
				{
					this._Request_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request Header]", Storage="_Request_Header", DbType="VarChar(100)")]
		public string Request_Header
		{
			get
			{
				return this._Request_Header;
			}
			set
			{
				if ((this._Request_Header != value))
				{
					this._Request_Header = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Requested]", Storage="_Date_Requested", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Requested
		{
			get
			{
				return this._Date_Requested;
			}
			set
			{
				if ((this._Date_Requested != value))
				{
					this._Date_Requested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_EquipmentViewResult
	{
		
		private int _equipment_id;
		
		private string _EQUIPMENT_NAME;
		
		private string _equipment_description;
		
		private System.Nullable<int> _equipment_type_id;
		
		private System.Nullable<int> _equipment_quantity;
		
		public sp_EquipmentViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment_id", DbType="Int NOT NULL")]
		public int equipment_id
		{
			get
			{
				return this._equipment_id;
			}
			set
			{
				if ((this._equipment_id != value))
				{
					this._equipment_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_NAME", DbType="VarChar(200)")]
		public string EQUIPMENT_NAME
		{
			get
			{
				return this._EQUIPMENT_NAME;
			}
			set
			{
				if ((this._EQUIPMENT_NAME != value))
				{
					this._EQUIPMENT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment_description", DbType="VarChar(100)")]
		public string equipment_description
		{
			get
			{
				return this._equipment_description;
			}
			set
			{
				if ((this._equipment_description != value))
				{
					this._equipment_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment_type_id", DbType="Int")]
		public System.Nullable<int> equipment_type_id
		{
			get
			{
				return this._equipment_type_id;
			}
			set
			{
				if ((this._equipment_type_id != value))
				{
					this._equipment_type_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment_quantity", DbType="Int")]
		public System.Nullable<int> equipment_quantity
		{
			get
			{
				return this._equipment_quantity;
			}
			set
			{
				if ((this._equipment_quantity != value))
				{
					this._equipment_quantity = value;
				}
			}
		}
	}
	
	public partial class sp_StudentSearchResult
	{
		
		private int _GENID;
		
		private string _USERNAME;
		
		private string _NAME;
		
		public sp_StudentSearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", DbType="Int NOT NULL")]
		public int GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this._GENID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
	}
	
	public partial class sp_StudentViewResult
	{
		
		private int _GENID;
		
		private string _USERNAME;
		
		private string _NAME;
		
		public sp_StudentViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENID", DbType="Int NOT NULL")]
		public int GENID
		{
			get
			{
				return this._GENID;
			}
			set
			{
				if ((this._GENID != value))
				{
					this._GENID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(200)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
	}
	
	public partial class sp_UserLoginResult
	{
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		public sp_UserLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(MAX)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
	}
	
	public partial class sp_UserReturnIDResult
	{
		
		private System.Nullable<int> _USERTYPE_ID;
		
		public sp_UserReturnIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERTYPE_ID", DbType="Int")]
		public System.Nullable<int> USERTYPE_ID
		{
			get
			{
				return this._USERTYPE_ID;
			}
			set
			{
				if ((this._USERTYPE_ID != value))
				{
					this._USERTYPE_ID = value;
				}
			}
		}
	}
	
	public partial class sp_UserSearchResult
	{
		
		private int _General_ID;
		
		private string _ID;
		
		private string _Username;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private string _Last_Name;
		
		private string _Contact_Number;
		
		private System.Nullable<int> _User_Type;
		
		public sp_UserSearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[General ID]", Storage="_General_ID", DbType="Int NOT NULL")]
		public int General_ID
		{
			get
			{
				return this._General_ID;
			}
			set
			{
				if ((this._General_ID != value))
				{
					this._General_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(150)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Middle Name]", Storage="_Middle_Name", DbType="VarChar(50)")]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this._Middle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact Number]", Storage="_Contact_Number", DbType="VarChar(20)")]
		public string Contact_Number
		{
			get
			{
				return this._Contact_Number;
			}
			set
			{
				if ((this._Contact_Number != value))
				{
					this._Contact_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User Type]", Storage="_User_Type", DbType="Int")]
		public System.Nullable<int> User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this._User_Type = value;
				}
			}
		}
	}
	
	public partial class sp_UserSearchAdminResult
	{
		
		private string _ID;
		
		private string _Username;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private string _Last_Name;
		
		public sp_UserSearchAdminResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(150)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Middle Name]", Storage="_Middle_Name", DbType="VarChar(50)")]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this._Middle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
	}
	
	public partial class sp_UserViewResult
	{
		
		private int _General_ID;
		
		private string _ID;
		
		private string _Username;
		
		private string _First_Name;
		
		private string _Middle_Name;
		
		private string _Last_Name;
		
		private string _Contact_Number;
		
		private System.Nullable<int> _User_Type;
		
		public sp_UserViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[General ID]", Storage="_General_ID", DbType="Int NOT NULL")]
		public int General_ID
		{
			get
			{
				return this._General_ID;
			}
			set
			{
				if ((this._General_ID != value))
				{
					this._General_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(150)")]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Middle Name]", Storage="_Middle_Name", DbType="VarChar(50)")]
		public string Middle_Name
		{
			get
			{
				return this._Middle_Name;
			}
			set
			{
				if ((this._Middle_Name != value))
				{
					this._Middle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100)")]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact Number]", Storage="_Contact_Number", DbType="VarChar(20)")]
		public string Contact_Number
		{
			get
			{
				return this._Contact_Number;
			}
			set
			{
				if ((this._Contact_Number != value))
				{
					this._Contact_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User Type]", Storage="_User_Type", DbType="Int")]
		public System.Nullable<int> User_Type
		{
			get
			{
				return this._User_Type;
			}
			set
			{
				if ((this._User_Type != value))
				{
					this._User_Type = value;
				}
			}
		}
	}
	
	public partial class sp_ViewAllRequestResult
	{
		
		private int _Request_ID;
		
		private string _Username;
		
		private string _Request_Header;
		
		private System.Nullable<System.DateTime> _Date_Requested;
		
		private string _Status;
		
		public sp_ViewAllRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request ID]", Storage="_Request_ID", DbType="Int NOT NULL")]
		public int Request_ID
		{
			get
			{
				return this._Request_ID;
			}
			set
			{
				if ((this._Request_ID != value))
				{
					this._Request_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request Header]", Storage="_Request_Header", DbType="VarChar(100)")]
		public string Request_Header
		{
			get
			{
				return this._Request_Header;
			}
			set
			{
				if ((this._Request_Header != value))
				{
					this._Request_Header = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Requested]", Storage="_Date_Requested", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Requested
		{
			get
			{
				return this._Date_Requested;
			}
			set
			{
				if ((this._Date_Requested != value))
				{
					this._Date_Requested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_ViewClosedRequestResult
	{
		
		private int _Request_ID;
		
		private string _Username;
		
		private string _Request_Header;
		
		private System.Nullable<System.DateTime> _Date_Requested;
		
		private string _Status;
		
		public sp_ViewClosedRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request ID]", Storage="_Request_ID", DbType="Int NOT NULL")]
		public int Request_ID
		{
			get
			{
				return this._Request_ID;
			}
			set
			{
				if ((this._Request_ID != value))
				{
					this._Request_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request Header]", Storage="_Request_Header", DbType="VarChar(100)")]
		public string Request_Header
		{
			get
			{
				return this._Request_Header;
			}
			set
			{
				if ((this._Request_Header != value))
				{
					this._Request_Header = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Requested]", Storage="_Date_Requested", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Requested
		{
			get
			{
				return this._Date_Requested;
			}
			set
			{
				if ((this._Date_Requested != value))
				{
					this._Date_Requested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class sp_ViewOpenRequestResult
	{
		
		private int _Request_ID;
		
		private string _Username;
		
		private string _Request_Header;
		
		private System.Nullable<System.DateTime> _Date_Requested;
		
		private string _Status;
		
		public sp_ViewOpenRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request ID]", Storage="_Request_ID", DbType="Int NOT NULL")]
		public int Request_ID
		{
			get
			{
				return this._Request_ID;
			}
			set
			{
				if ((this._Request_ID != value))
				{
					this._Request_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Request Header]", Storage="_Request_Header", DbType="VarChar(100)")]
		public string Request_Header
		{
			get
			{
				return this._Request_Header;
			}
			set
			{
				if ((this._Request_Header != value))
				{
					this._Request_Header = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Requested]", Storage="_Date_Requested", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Requested
		{
			get
			{
				return this._Date_Requested;
			}
			set
			{
				if ((this._Date_Requested != value))
				{
					this._Date_Requested = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
