<?xml version="1.0" encoding="utf-8"?><Database Name="ANS_SEIS_TV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NATHANIEL-VX15\NATHANIEL;Initial Catalog=ANS_SEIS_TV;Integrated Security=True" SettingsObjectName="ANS_SEIS_TV.Properties.Settings" SettingsPropertyName="ANS_SEIS_TVConnectionString1" Provider="System.Data.SqlClient" />

  <Table Name="dbo.REQUESTSTATUS" Member="REQUESTSTATUS">
    <Type Name="REQUESTSTATUS">
      <Column Name="REQUESTSTATUSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATUSDESCRIPTION" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="REQUESTSTATUS_TBLREQUESTTABLE" Member="TBLREQUESTTABLEs" ThisKey="REQUESTSTATUSID" OtherKey="REQUESTSTATUSID" Type="TBLREQUESTTABLE" />
    </Type>
  </Table>

  <Table Name="dbo.USERTYPE" Member="USERTYPEs">
    <Type Name="USERTYPE">
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERTYPE_DESCRIPTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="USERTYPE_TBLUSERDETAIL" Member="TBLUSERDETAILs" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="TBLUSERDETAIL" />

    </Type>
  </Table>
  <Table Name="dbo.STUDENTS" Member="STUDENTs">
    <Type Name="STUDENT">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQEUIPMENTTYPE" Member="TBLEQEUIPMENTTYPEs">
    <Type Name="TBLEQEUIPMENTTYPE">
      <Column Name="EQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_TYPE_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBLEQEUIPMENTTYPE_TBLEQUIPMENTDETAIL" Member="TBLEQUIPMENTDETAILs" ThisKey="EQUIPMENT_TYPE_ID" OtherKey="EQUIPMENT_TYPE_ID" Type="TBLEQUIPMENTDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.TBLEQUIPMENTDETAILS" Member="TBLEQUIPMENTDETAILs">
    <Type Name="TBLEQUIPMENTDETAIL">
      <Column Name="EQUIPMENT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EQBARCODE" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISBORROWABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBLEQEUIPMENTTYPE_TBLEQUIPMENTDETAIL" Member="TBLEQEUIPMENTTYPE" ThisKey="EQUIPMENT_TYPE_ID" OtherKey="EQUIPMENT_TYPE_ID" Type="TBLEQEUIPMENTTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLREQUESTTABLE" Member="TBLREQUESTTABLEs">
    <Type Name="TBLREQUESTTABLE">
      <Column Name="REQUESTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REQUESTHEADER" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REQUESTCONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATEREQUESTED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REQUESTSTATUSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISOPENED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="REQUESTSTATUS_TBLREQUESTTABLE" Member="REQUESTSTATUS" ThisKey="REQUESTSTATUSID" OtherKey="REQUESTSTATUSID" Type="REQUESTSTATUS" IsForeignKey="true" />
      <Association Name="TBLUSERDETAIL_TBLREQUESTTABLE" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs">
    <Type Name="TBLUSERACTIONREPORT">
      <Column Name="ActionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />

      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_TBLUSERLOGINREPORT" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERDETAILS" Member="TBLUSERDETAILs">
    <Type Name="TBLUSERDETAIL">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISFIRSTLOGIN" Type="System.Int32" DbType="Int" CanBeNull="true" />

      <Association Name="TBLUSERDETAIL_TBLREQUESTTABLE" Member="TBLREQUESTTABLEs" ThisKey="GENID" OtherKey="GENID" Type="TBLREQUESTTABLE" />
      <Association Name="TBLUSERDETAIL_TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERACTIONREPORT" />

      <Association Name="TBLUSERDETAIL_TBLUSERLOGINREPORT" Member="TBLUSERLOGINREPORTs" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERLOGINREPORT" />
      <Association Name="TBLUSERDETAIL_TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERACTIONREPORT" />
      <Association Name="TBLUSERDETAIL_EQUIPMENT_DESIGNATION" Member="EQUIPMENT_DESIGNATIONs" ThisKey="GENID" OtherKey="GENID" Type="EQUIPMENT_DESIGNATION" />
      <Association Name="USERTYPE_TBLUSERDETAIL" Member="USERTYPE" ThisKey="USERTYPE_ID" OtherKey="USERTYPE_ID" Type="USERTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBLUSERACTIONREPORT" Member="TBLUSERACTIONREPORTs">
    <Type Name="TBLUSERACTIONREPORT">
      <Column Name="ActionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />

      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBLUSERDETAIL_TBLUSERLOGINREPORT" Member="TBLUSERDETAIL" ThisKey="GENID" OtherKey="GENID" Type="TBLUSERDETAIL" IsForeignKey="true" />

    </Type>
  </Table>
  <Function Name="dbo.sp_EquipmentDelete" Method="sp_EquipmentDelete">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ViewPendingRequest" Method="sp_ViewPendingRequest">
    <ElementType Name="sp_ViewPendingRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_EquipmentEdit" Method="sp_EquipmentEdit">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQBARCODE" Parameter="eQBARCODE" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_NAME" Parameter="eQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="EQUIPMENT_DESCRIPTION" Parameter="eQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_TYPE_ID" Parameter="eQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentID" Method="sp_EquipmentID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentQuantityEdit" Method="sp_EquipmentQuantityEdit">
    <Parameter Name="EQUIPMENT_ID" Parameter="eQUIPMENT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentRegister" Method="sp_EquipmentRegister">
    <Parameter Name="EQBARCODE" Parameter="eQBARCODE" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_NAME" Parameter="eQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="EQUIPMENT_DESCRIPTION" Parameter="eQUIPMENT_DESCRIPTION" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="EQUIPMENT_TYPE_ID" Parameter="eQUIPMENT_TYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="EQUIPMENT_QUANTITY" Parameter="eQUIPMENT_QUANTITY" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISBORROWABLE" Parameter="iSBORROWABLE" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EquipmentView" Method="sp_EquipmentView">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_EquipmentViewResult">
      <Column Name="equipment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EQUIPMENT_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="equipment_description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="equipment_type_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="equipment_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_NewRequest" Method="sp_NewRequest">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="REQUESTHEADER" Parameter="rEQUESTHEADER" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="REQUESTCONTENT" Parameter="rEQUESTCONTENT" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DATEREQUESTED" Parameter="dATEREQUESTED" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="REQUESTSTATUSID" Parameter="rEQUESTSTATUSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISOPENED" Parameter="iSOPENED" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_StudentInsert" Method="sp_StudentInsert">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_StudentSearch" Method="sp_StudentSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_StudentSearchResult">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StudentView" Method="sp_StudentView">
    <ElementType Name="sp_StudentViewResult">
      <Column Name="GENID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserActionReport" Method="sp_UserActionReport">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserActionReportView" Method="sp_UserActionReportView">
    <ElementType Name="sp_UserActionReportViewResult">
      <Column Name="ActionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GENID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserDelete" Method="sp_UserDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserEdit" Method="sp_UserEdit">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="FIRSTNAME" Parameter="fIRSTNAME" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="MIDDLENAME" Parameter="mIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LASTNAME" Parameter="lASTNAME" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CONTACT_NUMBER" Parameter="cONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USERTYPE_ID" Parameter="uSERTYPE_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserFirstLogin" Method="sp_UserFirstLogin">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserFirstLoginEdit" Method="sp_UserFirstLoginEdit">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISFIRSTLOGIN" Parameter="iSFIRSTLOGIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserID" Method="sp_UserID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserInsert" Method="sp_UserInsert">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="FIRSTNAME" Parameter="fIRSTNAME" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="MIDDLENAME" Parameter="mIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LASTNAME" Parameter="lASTNAME" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CONTACT_NUMBER" Parameter="cONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SECURITY_QUESTION" Parameter="sECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SECURITY_ANSWER" Parameter="sECURITY_ANSWER" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="USERTYPE_ID" Parameter="uSERTYPE_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISFIRSTLOGIN" Parameter="iSFIRSTLOGIN" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserLogin" Method="sp_UserLogin">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_UserLoginResult">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserLoginReport" Method="sp_UserLoginReport">
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />

    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserReturnID" Method="sp_UserReturnID">
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="GENID" Parameter="gENID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UserReturnIDResult">
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserSearch" Method="sp_UserSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_UserSearchResult">
      <Column Name="[General ID]" Member="General_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[User Type]" Member="User_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserView" Method="sp_UserView">
    <ElementType Name="sp_UserViewResult">
      <Column Name="[General ID]" Member="General_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="[Middle Name]" Member="Middle_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Contact Number]" Member="Contact_Number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[User Type]" Member="User_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewAllRequest" Method="sp_ViewAllRequest">
    <ElementType Name="sp_ViewAllRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewClosedRequest" Method="sp_ViewClosedRequest">
    <ElementType Name="sp_ViewClosedRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewOpenRequest" Method="sp_ViewOpenRequest">
    <ElementType Name="sp_ViewOpenRequestResult">
      <Column Name="[Request ID]" Member="Request_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Request Header]" Member="Request_Header" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="[Date Requested]" Member="Date_Requested" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>