namespace ANS_SEIS_TV
{
    partial class EquipmentRegistration
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing && (components != null))
        //    {
        //        components.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        //private void InitializeComponent()
        //{
        //    this.cmbUserType = new DevComponents.DotNetBar.Controls.ComboBoxEx();
        //    this.lblGenID = new DevComponents.DotNetBar.LabelX();
        //    this.txtMname = new DevComponents.DotNetBar.Controls.TextBoxX();
        //    this.txtFname = new DevComponents.DotNetBar.Controls.TextBoxX();
        //    this.label7 = new System.Windows.Forms.Label();
        //    this.label6 = new System.Windows.Forms.Label();
        //    this.label5 = new System.Windows.Forms.Label();
        //    this.label3 = new System.Windows.Forms.Label();
        //    this.label2 = new System.Windows.Forms.Label();
        //    this.label1 = new System.Windows.Forms.Label();
        //    this.comboBoxEx1 = new DevComponents.DotNetBar.Controls.ComboBoxEx();
        //    this.label4 = new System.Windows.Forms.Label();
        //    this.comboBoxEx2 = new DevComponents.DotNetBar.Controls.ComboBoxEx();
        //    this.label10 = new System.Windows.Forms.Label();
        //    this.comboBoxEx3 = new DevComponents.DotNetBar.Controls.ComboBoxEx();
        //    this.button2 = new System.Windows.Forms.Button();
        //    this.button1 = new System.Windows.Forms.Button();
        //    this.SuspendLayout();
        //    // 
        //    // cmbUserType
        //    // 
        //    this.cmbUserType.DisplayMember = "Text";
        //    this.cmbUserType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
        //    this.cmbUserType.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.cmbUserType.FormattingEnabled = true;
        //    this.cmbUserType.ItemHeight = 17;
        //    this.cmbUserType.Location = new System.Drawing.Point(223, 182);
        //    this.cmbUserType.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.cmbUserType.Name = "cmbUserType";
        //    this.cmbUserType.Size = new System.Drawing.Size(337, 23);
        //    this.cmbUserType.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
        //    this.cmbUserType.TabIndex = 36;
        //    this.cmbUserType.WatermarkText = "Furniture, appliance,etc";
        //    // 
        //    // lblGenID
        //    // 
        //    // 
        //    // 
        //    // 
        //    this.lblGenID.BackgroundStyle.Class = "";
        //    this.lblGenID.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.lblGenID.ForeColor = System.Drawing.Color.MistyRose;
        //    this.lblGenID.Location = new System.Drawing.Point(223, 123);
        //    this.lblGenID.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.lblGenID.Name = "lblGenID";
        //    this.lblGenID.Size = new System.Drawing.Size(339, 35);
        //    this.lblGenID.TabIndex = 35;
        //    this.lblGenID.Text = "AUTOGENERATED";
        //    // 
        //    // txtMname
        //    // 
        //    // 
        //    // 
        //    // 
        //    this.txtMname.Border.Class = "TextBoxBorder";
        //    this.txtMname.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.txtMname.Location = new System.Drawing.Point(784, 276);
        //    this.txtMname.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.txtMname.Multiline = true;
        //    this.txtMname.Name = "txtMname";
        //    this.txtMname.Size = new System.Drawing.Size(339, 40);
        //    this.txtMname.TabIndex = 32;
        //    this.txtMname.WatermarkText = "Orginal serial number of product";
        //    // 
        //    // txtFname
        //    // 
        //    // 
        //    // 
        //    // 
        //    this.txtFname.Border.Class = "TextBoxBorder";
        //    this.txtFname.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.txtFname.Location = new System.Drawing.Point(223, 239);
        //    this.txtFname.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.txtFname.Multiline = true;
        //    this.txtFname.Name = "txtFname";
        //    this.txtFname.Size = new System.Drawing.Size(339, 40);
        //    this.txtFname.TabIndex = 30;
        //    this.txtFname.WatermarkText = "Item name";
        //    // 
        //    // label7
        //    // 
        //    this.label7.AutoSize = true;
        //    this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label7.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label7.Location = new System.Drawing.Point(613, 286);
        //    this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label7.Name = "label7";
        //    this.label7.Size = new System.Drawing.Size(107, 20);
        //    this.label7.TabIndex = 27;
        //    this.label7.Text = "Serial number";
        //    // 
        //    // label6
        //    // 
        //    this.label6.AutoSize = true;
        //    this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label6.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label6.Location = new System.Drawing.Point(611, 235);
        //    this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label6.Name = "label6";
        //    this.label6.Size = new System.Drawing.Size(104, 20);
        //    this.label6.TabIndex = 26;
        //    this.label6.Text = "Manufacturer";
        //    // 
        //    // label5
        //    // 
        //    this.label5.AutoSize = true;
        //    this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label5.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label5.Location = new System.Drawing.Point(47, 249);
        //    this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label5.Name = "label5";
        //    this.label5.Size = new System.Drawing.Size(48, 20);
        //    this.label5.TabIndex = 25;
        //    this.label5.Text = "Label";
        //    // 
        //    // label3
        //    // 
        //    this.label3.AutoSize = true;
        //    this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label3.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label3.Location = new System.Drawing.Point(48, 183);
        //    this.label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label3.Name = "label3";
        //    this.label3.Size = new System.Drawing.Size(124, 20);
        //    this.label3.TabIndex = 23;
        //    this.label3.Text = "Equipment Type";
        //    // 
        //    // label2
        //    // 
        //    this.label2.AutoSize = true;
        //    this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label2.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label2.Location = new System.Drawing.Point(48, 129);
        //    this.label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label2.Name = "label2";
        //    this.label2.Size = new System.Drawing.Size(125, 20);
        //    this.label2.TabIndex = 22;
        //    this.label2.Text = "Equipment code";
        //    // 
        //    // label1
        //    // 
        //    this.label1.AutoSize = true;
        //    this.label1.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
        //    this.label1.ForeColor = System.Drawing.Color.Snow;
        //    this.label1.Location = new System.Drawing.Point(46, 40);
        //    this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label1.Name = "label1";
        //    this.label1.Size = new System.Drawing.Size(262, 25);
        //    this.label1.TabIndex = 21;
        //    this.label1.Text = "REGISTER NEW EQUIPMENT";
        //    // 
        //    // comboBoxEx1
        //    // 
        //    this.comboBoxEx1.DisplayMember = "Text";
        //    this.comboBoxEx1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
        //    this.comboBoxEx1.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.comboBoxEx1.FormattingEnabled = true;
        //    this.comboBoxEx1.ItemHeight = 17;
        //    this.comboBoxEx1.Location = new System.Drawing.Point(223, 307);
        //    this.comboBoxEx1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.comboBoxEx1.Name = "comboBoxEx1";
        //    this.comboBoxEx1.Size = new System.Drawing.Size(337, 23);
        //    this.comboBoxEx1.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
        //    this.comboBoxEx1.TabIndex = 38;
        //    this.comboBoxEx1.WatermarkText = "Initial location of item";
        //    // 
        //    // label4
        //    // 
        //    this.label4.AutoSize = true;
        //    this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label4.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label4.Location = new System.Drawing.Point(48, 308);
        //    this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label4.Name = "label4";
        //    this.label4.Size = new System.Drawing.Size(94, 20);
        //    this.label4.TabIndex = 37;
        //    this.label4.Text = "Designation";
        //    // 
        //    // comboBoxEx2
        //    // 
        //    this.comboBoxEx2.DisplayMember = "Text";
        //    this.comboBoxEx2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
        //    this.comboBoxEx2.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.comboBoxEx2.FormattingEnabled = true;
        //    this.comboBoxEx2.ItemHeight = 17;
        //    this.comboBoxEx2.Location = new System.Drawing.Point(784, 229);
        //    this.comboBoxEx2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.comboBoxEx2.Name = "comboBoxEx2";
        //    this.comboBoxEx2.Size = new System.Drawing.Size(337, 23);
        //    this.comboBoxEx2.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
        //    this.comboBoxEx2.TabIndex = 39;
        //    this.comboBoxEx2.WatermarkText = "Manufactured by";
        //    // 
        //    // label10
        //    // 
        //    this.label10.AutoSize = true;
        //    this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        //    this.label10.ForeColor = System.Drawing.Color.MistyRose;
        //    this.label10.Location = new System.Drawing.Point(611, 182);
        //    this.label10.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
        //    this.label10.Name = "label10";
        //    this.label10.Size = new System.Drawing.Size(88, 20);
        //    this.label10.TabIndex = 40;
        //    this.label10.Text = "Item Brand";
        //    // 
        //    // comboBoxEx3
        //    // 
        //    this.comboBoxEx3.DisplayMember = "Text";
        //    this.comboBoxEx3.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
        //    this.comboBoxEx3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
        //    this.comboBoxEx3.FormattingEnabled = true;
        //    this.comboBoxEx3.ItemHeight = 17;
        //    this.comboBoxEx3.Location = new System.Drawing.Point(784, 182);
        //    this.comboBoxEx3.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
        //    this.comboBoxEx3.Name = "comboBoxEx3";
        //    this.comboBoxEx3.Size = new System.Drawing.Size(337, 23);
        //    this.comboBoxEx3.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
        //    this.comboBoxEx3.TabIndex = 41;
        //    this.comboBoxEx3.WatermarkText = "Brand of item";
        //    // 
        //    // button2
        //    // 
        //    this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        //    this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F);
        //    this.button2.ForeColor = System.Drawing.Color.WhiteSmoke;
        //    this.button2.Location = new System.Drawing.Point(1010, 544);
        //    this.button2.Name = "button2";
        //    this.button2.Size = new System.Drawing.Size(117, 39);
        //    this.button2.TabIndex = 43;
        //    this.button2.Text = "CANCEL";
        //    this.button2.UseVisualStyleBackColor = true;
        //    // 
        //    // button1
        //    // 
        //    this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
        //    this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F);
        //    this.button1.ForeColor = System.Drawing.Color.WhiteSmoke;
        //    this.button1.Location = new System.Drawing.Point(887, 544);
        //    this.button1.Name = "button1";
        //    this.button1.Size = new System.Drawing.Size(117, 39);
        //    this.button1.TabIndex = 42;
        //    this.button1.Text = "REGISTER";
        //    this.button1.UseVisualStyleBackColor = true;
        //    // 
        //    // EquipmentRegistration
        //    // 
        //    this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        //    this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        //    this.BackColor = System.Drawing.Color.IndianRed;
        //    this.ClientSize = new System.Drawing.Size(1200, 692);
        //    this.Controls.Add(this.button2);
        //    this.Controls.Add(this.button1);
        //    this.Controls.Add(this.comboBoxEx3);
        //    this.Controls.Add(this.label10);
        //    this.Controls.Add(this.comboBoxEx2);
        //    this.Controls.Add(this.comboBoxEx1);
        //    this.Controls.Add(this.label4);
        //    this.Controls.Add(this.cmbUserType);
        //    this.Controls.Add(this.lblGenID);
        //    this.Controls.Add(this.txtMname);
        //    this.Controls.Add(this.txtFname);
        //    this.Controls.Add(this.label7);
        //    this.Controls.Add(this.label6);
        //    this.Controls.Add(this.label5);
        //    this.Controls.Add(this.label3);
        //    this.Controls.Add(this.label2);
        //    this.Controls.Add(this.label1);
        //    this.Name = "EquipmentRegistration";
        //    this.Text = "EquipmentRegistration";
        //    this.ResumeLayout(false);
        //    this.PerformLayout();

        //}

        #endregion

        private DevComponents.DotNetBar.Controls.ComboBoxEx cmbUserType;
        private DevComponents.DotNetBar.LabelX lblGenID;
        private DevComponents.DotNetBar.Controls.TextBoxX txtMname;
        private DevComponents.DotNetBar.Controls.TextBoxX txtFname;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private DevComponents.DotNetBar.Controls.ComboBoxEx comboBoxEx1;
        private System.Windows.Forms.Label label4;
        private DevComponents.DotNetBar.Controls.ComboBoxEx comboBoxEx2;
        private System.Windows.Forms.Label label10;
        private DevComponents.DotNetBar.Controls.ComboBoxEx comboBoxEx3;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button1;
    }
}